# Generated by Django 3.2.7 on 2023-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='Profiles/default-user.png', null=True, upload_to='Profiles'),
        ),
    ]
